imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /api/storages/localfiles/
      method: GET
      auth: true
      docs: Get a list of all local file import storage connections.
      source:
        openapi: openapi/openapi.yaml
      display-name: Get all import storage
      request:
        name: LocalListRequest
        query-parameters:
          ordering:
            type: optional<string>
            docs: Which field to use when ordering the results.
          project:
            type: optional<integer>
            docs: Project ID
      response:
        docs: ''
        type: list<root.LocalFilesImportStorage>
      examples:
        - response:
            body:
              - id: 1
                type: type
                synchronizable: true
                path: path
                regex_filter: regex_filter
                use_blob_urls: true
                last_sync: '2024-01-15T09:30:00Z'
                last_sync_count: 1
                last_sync_job: last_sync_job
                status: initialized
                traceback: traceback
                meta:
                  key: value
                title: title
                description: description
                created_at: '2024-01-15T09:30:00Z'
                project: 1
      audiences:
        - public
    create:
      path: /api/storages/localfiles/
      method: POST
      auth: true
      docs: Create a new local file import storage connection.
      source:
        openapi: openapi/openapi.yaml
      display-name: Create import storage
      request:
        name: LocalCreateRequest
        body:
          properties:
            title:
              type: optional<string>
              docs: Storage title
              validation:
                maxLength: 2048
            description:
              type: optional<string>
              docs: Storage description
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Path to local directory
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: >-
                Interpret objects as BLOBs and generate URLs. For example, if
                your directory contains images, you can use this option to
                generate URLs for these images. If set to False, it will read
                the content of the file and load it into Label Studio.
              default: false
        content-type: application/json
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - request: {}
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
    get:
      path: /api/storages/localfiles/{id}
      method: GET
      auth: true
      docs: Get a specific local file import storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Get import storage
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
    delete:
      path: /api/storages/localfiles/{id}
      method: DELETE
      auth: true
      docs: Delete a specific local file import storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Delete import storage
      examples:
        - path-parameters:
            id: 1
      audiences:
        - public
    update:
      path: /api/storages/localfiles/{id}
      method: PATCH
      auth: true
      docs: Update a specific local file import storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Update import storage
      request:
        name: LocalUpdateRequest
        body:
          properties:
            title:
              type: optional<string>
              docs: Storage title
              validation:
                maxLength: 2048
            description:
              type: optional<string>
              docs: Storage description
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Path to local directory
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: >-
                Interpret objects as BLOBs and generate URLs. For example, if
                your directory contains images, you can use this option to
                generate URLs for these images. If set to False, it will read
                the content of the file and load it into Label Studio.
              default: false
        content-type: application/json
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - path-parameters:
            id: 1
          request: {}
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
    sync:
      path: /api/storages/localfiles/{id}/sync
      method: POST
      auth: true
      docs: Sync tasks from a local file import storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id:
          type: integer
          docs: Storage ID
      display-name: Sync import storage
      response:
        docs: ''
        type: root.LocalFilesImportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              id: 1
              type: type
              synchronizable: true
              path: path
              regex_filter: regex_filter
              use_blob_urls: true
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              status: initialized
              traceback: traceback
              meta:
                key: value
              title: title
              description: description
              created_at: '2024-01-15T09:30:00Z'
              project: 1
      audiences:
        - public
    validate:
      path: /api/storages/localfiles/validate
      method: POST
      auth: true
      docs: Validate a specific local file import storage connection.
      source:
        openapi: openapi/openapi.yaml
      display-name: Validate import storage
      request:
        name: LocalValidateRequest
        body:
          properties:
            id:
              type: optional<integer>
              docs: Storage ID. If set, storage with specified ID will be updated
            title:
              type: optional<string>
              docs: Storage title
              validation:
                maxLength: 2048
            description:
              type: optional<string>
              docs: Storage description
            project:
              type: optional<integer>
              docs: Project ID
            path:
              type: optional<string>
              docs: Path to local directory
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            use_blob_urls:
              type: optional<boolean>
              docs: >-
                Interpret objects as BLOBs and generate URLs. For example, if
                your directory contains images, you can use this option to
                generate URLs for these images. If set to False, it will read
                the content of the file and load it into Label Studio.
              default: false
        content-type: application/json
      examples:
        - request: {}
      audiences:
        - public
  source:
    openapi: openapi/openapi.yaml
