# This file was auto-generated by Fern from our API Definition.

from .assign_assignments_request_type import AssignAssignmentsRequestType
from .bulk_assign_assignments_request_filters import BulkAssignAssignmentsRequestFilters
from .bulk_assign_assignments_request_filters_conjunction import BulkAssignAssignmentsRequestFiltersConjunction
from .bulk_assign_assignments_request_filters_items_item import BulkAssignAssignmentsRequestFiltersItemsItem
from .bulk_assign_assignments_request_filters_items_item_filter import (
    BulkAssignAssignmentsRequestFiltersItemsItemFilter,
)
from .bulk_assign_assignments_request_filters_items_item_operator import (
    BulkAssignAssignmentsRequestFiltersItemsItemOperator,
)
from .bulk_assign_assignments_request_filters_items_item_value import BulkAssignAssignmentsRequestFiltersItemsItemValue
from .bulk_assign_assignments_request_selected_items import BulkAssignAssignmentsRequestSelectedItems
from .bulk_assign_assignments_request_selected_items_excluded import BulkAssignAssignmentsRequestSelectedItemsExcluded
from .bulk_assign_assignments_request_selected_items_included import BulkAssignAssignmentsRequestSelectedItemsIncluded
from .bulk_assign_assignments_request_type import BulkAssignAssignmentsRequestType
from .bulk_assign_assignments_response import BulkAssignAssignmentsResponse
from .delete_assignments_request_type import DeleteAssignmentsRequestType
from .update_assignments_request_type import UpdateAssignmentsRequestType

__all__ = [
    "AssignAssignmentsRequestType",
    "BulkAssignAssignmentsRequestFilters",
    "BulkAssignAssignmentsRequestFiltersConjunction",
    "BulkAssignAssignmentsRequestFiltersItemsItem",
    "BulkAssignAssignmentsRequestFiltersItemsItemFilter",
    "BulkAssignAssignmentsRequestFiltersItemsItemOperator",
    "BulkAssignAssignmentsRequestFiltersItemsItemValue",
    "BulkAssignAssignmentsRequestSelectedItems",
    "BulkAssignAssignmentsRequestSelectedItemsExcluded",
    "BulkAssignAssignmentsRequestSelectedItemsIncluded",
    "BulkAssignAssignmentsRequestType",
    "BulkAssignAssignmentsResponse",
    "DeleteAssignmentsRequestType",
    "UpdateAssignmentsRequestType",
]
