# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.serialization import FieldMetadata
from ....core.unchecked_base_model import UncheckedBaseModel


class BulkAssignAssignmentsRequestSelectedItemsExcluded(UncheckedBaseModel):
    all_: typing_extensions.Annotated[
        bool, FieldMetadata(alias="all"), pydantic.Field(alias="all", description="All tasks are selected")
    ]
    excluded: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    List of excluded task IDs
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
