# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class KpiTimeSegment(UncheckedBaseModel):
    """
    Serializer for time-segmented KPI data (compact format).
    Returns parallel arrays: interval_start and values.
    """

    interval_start: typing.List[dt.datetime] = pydantic.Field()
    """
    Array of time period start timestamps
    """

    values: typing.List[typing.Optional[float]] = pydantic.Field()
    """
    Array of KPI values, one per time period (parallel to interval_start)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
