# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Workspace(UncheckedBaseModel):
    """
    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations
    """

    id: int
    title: str = pydantic.Field()
    """
    Workspace name
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workspace description
    """

    color: typing.Optional[str] = None
    is_personal: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Workspace is a personal user workspace
    """

    is_archived: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Workspace is archived
    """

    created_by: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
