# This file was auto-generated by Fern from our API Definition.

from label_studio_sdk import LabelStudio
from label_studio_sdk import AsyncLabelStudio
import typing
from .utilities import validate_response


async def test_batch_failed_predictions(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = {"job_id": "job_id", "failed_predictions": [{"key": "value"}]}
    expected_types: typing.Any = {"job_id": None, "failed_predictions": ("list", {0: None})}
    response = client.prompts.batch_failed_predictions(failed_predictions=[], modelrun_id=1)
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.batch_failed_predictions(failed_predictions=[], modelrun_id=1)
    validate_response(async_response, expected_response, expected_types)


async def test_batch_predictions(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = {"job_id": "job_id", "results": [{"key": "value"}]}
    expected_types: typing.Any = {"job_id": None, "results": ("list", {0: None})}
    response = client.prompts.batch_predictions(results=[], modelrun_id=1)
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.batch_predictions(results=[], modelrun_id=1)
    validate_response(async_response, expected_response, expected_types)


async def test_list_(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = [
        {
            "id": 1,
            "created_by": {
                "id": 1,
                "first_name": "first_name",
                "last_name": "last_name",
                "email": "email",
                "avatar": "avatar",
            },
            "skill_name": "TextClassification",
            "associated_projects": [{"id": 1}],
            "title": "title",
            "description": "description",
            "created_at": "2024-01-15T09:30:00Z",
            "updated_at": "2024-01-15T09:30:00Z",
            "input_fields": {"key": "value"},
            "output_classes": {"key": "value"},
            "organization": 1,
        }
    ]
    expected_types: typing.Tuple[typing.Any, typing.Any] = (
        "list",
        {
            0: {
                "id": "integer",
                "created_by": {"id": "integer", "first_name": None, "last_name": None, "email": None, "avatar": None},
                "skill_name": None,
                "associated_projects": ("list", {0: {"id": "integer"}}),
                "title": None,
                "description": None,
                "created_at": "datetime",
                "updated_at": "datetime",
                "input_fields": None,
                "output_classes": None,
                "organization": "integer",
            }
        },
    )
    response = client.prompts.list()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.list()
    validate_response(async_response, expected_response, expected_types)


async def test_create(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = {
        "id": 1,
        "created_by": {
            "id": 1,
            "first_name": "first_name",
            "last_name": "last_name",
            "email": "email",
            "avatar": "avatar",
        },
        "skill_name": "TextClassification",
        "title": "title",
        "description": "description",
        "created_at": "2024-01-15T09:30:00Z",
        "updated_at": "2024-01-15T09:30:00Z",
        "input_fields": {"key": "value"},
        "output_classes": {"key": "value"},
        "organization": 1,
        "associated_projects": [1],
    }
    expected_types: typing.Any = {
        "id": "integer",
        "created_by": {"id": "integer", "first_name": None, "last_name": None, "email": None, "avatar": None},
        "skill_name": None,
        "title": None,
        "description": None,
        "created_at": "datetime",
        "updated_at": "datetime",
        "input_fields": None,
        "output_classes": None,
        "organization": "integer",
        "associated_projects": ("list", {0: "integer"}),
    }
    response = client.prompts.create(title="title")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.create(title="title")
    validate_response(async_response, expected_response, expected_types)


async def test_get(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = {
        "id": 1,
        "created_by": {
            "id": 1,
            "first_name": "first_name",
            "last_name": "last_name",
            "email": "email",
            "avatar": "avatar",
        },
        "skill_name": "TextClassification",
        "associated_projects": [{"id": 1, "title": "title"}],
        "title": "title",
        "description": "description",
        "created_at": "2024-01-15T09:30:00Z",
        "updated_at": "2024-01-15T09:30:00Z",
        "input_fields": {"key": "value"},
        "output_classes": {"key": "value"},
        "organization": 1,
    }
    expected_types: typing.Any = {
        "id": "integer",
        "created_by": {"id": "integer", "first_name": None, "last_name": None, "email": None, "avatar": None},
        "skill_name": None,
        "associated_projects": ("list", {0: {"id": "integer", "title": None}}),
        "title": None,
        "description": None,
        "created_at": "datetime",
        "updated_at": "datetime",
        "input_fields": None,
        "output_classes": None,
        "organization": "integer",
    }
    response = client.prompts.get(id="id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.get(id="id")
    validate_response(async_response, expected_response, expected_types)


async def test_delete(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert (
        client.prompts.delete(id="id")  # type: ignore[func-returns-value]
        is None
    )

    assert (
        await async_client.prompts.delete(id="id")  # type: ignore[func-returns-value]
        is None
    )


async def test_update(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = {
        "id": 1,
        "created_by": {
            "id": 1,
            "first_name": "first_name",
            "last_name": "last_name",
            "email": "email",
            "avatar": "avatar",
        },
        "skill_name": "TextClassification",
        "title": "title",
        "description": "description",
        "created_at": "2024-01-15T09:30:00Z",
        "updated_at": "2024-01-15T09:30:00Z",
        "input_fields": {"key": "value"},
        "output_classes": {"key": "value"},
        "organization": 1,
        "associated_projects": [1],
    }
    expected_types: typing.Any = {
        "id": "integer",
        "created_by": {"id": "integer", "first_name": None, "last_name": None, "email": None, "avatar": None},
        "skill_name": None,
        "title": None,
        "description": None,
        "created_at": "datetime",
        "updated_at": "datetime",
        "input_fields": None,
        "output_classes": None,
        "organization": "integer",
        "associated_projects": ("list", {0: "integer"}),
    }
    response = client.prompts.update(id="id")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.update(id="id")
    validate_response(async_response, expected_response, expected_types)


async def test_compatible_projects(client: LabelStudio, async_client: AsyncLabelStudio) -> None:
    expected_response: typing.Any = {
        "count": 123,
        "next": "http://api.example.org/accounts/?page=4",
        "previous": "http://api.example.org/accounts/?page=2",
        "results": [
            {
                "model_version": "model_version",
                "reveal_preannotations_interactively": True,
                "config_suitable_for_bulk_annotation": True,
                "custom_script": "custom_script",
                "reviewed_number": "reviewed_number",
                "show_skip_button": True,
                "workspace": "workspace",
                "rejected": "rejected",
                "created_by": {"id": 1, "avatar": "avatar"},
                "is_draft": True,
                "parsed_label_config": {"key": "value"},
                "blueprints": [
                    {"id": 1, "share_id": "share_id", "short_url": "short_url", "created_at": "2024-01-15T09:30:00Z"}
                ],
                "allow_stream": "allow_stream",
                "members_count": 1,
                "label_config": "label_config",
                "maximum_annotations": 1,
                "show_instruction": True,
                "total_annotations_number": "total_annotations_number",
                "reviewer_queue_total": "reviewer_queue_total",
                "show_overlap_first": True,
                "comment_classification_config": "comment_classification_config",
                "created_at": "2024-01-15T09:30:00Z",
                "useful_annotation_number": "useful_annotation_number",
                "min_annotations_to_start_training": 1,
                "organization": 1,
                "overlap_cohort_percentage": 1,
                "show_annotation_history": True,
                "config_has_control_tags": True,
                "id": 1,
                "pinned_at": "2024-01-15T09:30:00Z",
                "review_settings": {"id": 1, "requeue_rejected_tasks_to_annotator": True},
                "data_types": {"key": "value"},
                "custom_task_lock_ttl": 1,
                "annotator_evaluation_minimum_tasks": 1,
                "annotation_limit_percent": "annotation_limit_percent",
                "annotation_limit_count": 1,
                "ready": "ready",
                "evaluate_predictions_automatically": True,
                "duplication_status": "duplication_status",
                "prompts": "prompts",
                "skipped_annotations_number": "skipped_annotations_number",
                "enable_empty_annotation": True,
                "color": "color",
                "start_training_on_annotation_update": True,
                "queue_left": "queue_left",
                "description_short": "description_short",
                "duplication_done": True,
                "members": "members",
                "pause_on_failed_annotator_evaluation": True,
                "has_blueprints": "has_blueprints",
                "show_collab_predictions": True,
                "title": "title",
                "total_predictions_number": 1,
                "review_total_tasks": "review_total_tasks",
                "expert_instruction": "expert_instruction",
                "num_tasks_with_annotations": "num_tasks_with_annotations",
                "annotator_evaluation_minimum_score": "annotator_evaluation_minimum_score",
                "finished_task_number": 1,
                "task_number": 1,
                "control_weights": {"key": "value"},
                "queue_done": "queue_done",
                "show_ground_truth_first": True,
                "assignment_settings": {"id": 1},
                "require_comment_on_skip": True,
                "ground_truth_number": 1,
                "skip_queue": "REQUEUE_FOR_ME",
                "workspace_title": "workspace_title",
                "sampling": "Sequential sampling",
                "queue_total": "queue_total",
                "is_published": True,
                "description": "description",
            }
        ],
    }
    expected_types: typing.Any = {
        "count": "integer",
        "next": None,
        "previous": None,
        "results": (
            "list",
            {
                0: {
                    "model_version": None,
                    "reveal_preannotations_interactively": None,
                    "config_suitable_for_bulk_annotation": None,
                    "custom_script": None,
                    "reviewed_number": None,
                    "show_skip_button": None,
                    "workspace": None,
                    "rejected": None,
                    "created_by": {"id": "integer", "avatar": None},
                    "is_draft": None,
                    "parsed_label_config": None,
                    "blueprints": (
                        "list",
                        {0: {"id": "integer", "share_id": None, "short_url": None, "created_at": "datetime"}},
                    ),
                    "allow_stream": None,
                    "members_count": "integer",
                    "label_config": None,
                    "maximum_annotations": "integer",
                    "show_instruction": None,
                    "total_annotations_number": None,
                    "reviewer_queue_total": None,
                    "show_overlap_first": None,
                    "comment_classification_config": None,
                    "created_at": "datetime",
                    "useful_annotation_number": None,
                    "min_annotations_to_start_training": "integer",
                    "organization": "integer",
                    "overlap_cohort_percentage": "integer",
                    "show_annotation_history": None,
                    "config_has_control_tags": None,
                    "id": "integer",
                    "pinned_at": "datetime",
                    "review_settings": {"id": "integer", "requeue_rejected_tasks_to_annotator": None},
                    "data_types": None,
                    "custom_task_lock_ttl": "integer",
                    "annotator_evaluation_minimum_tasks": "integer",
                    "annotation_limit_percent": None,
                    "annotation_limit_count": "integer",
                    "ready": None,
                    "evaluate_predictions_automatically": None,
                    "duplication_status": None,
                    "prompts": None,
                    "skipped_annotations_number": None,
                    "enable_empty_annotation": None,
                    "color": None,
                    "start_training_on_annotation_update": None,
                    "queue_left": None,
                    "description_short": None,
                    "duplication_done": None,
                    "members": None,
                    "pause_on_failed_annotator_evaluation": None,
                    "has_blueprints": None,
                    "show_collab_predictions": None,
                    "title": None,
                    "total_predictions_number": "integer",
                    "review_total_tasks": None,
                    "expert_instruction": None,
                    "num_tasks_with_annotations": None,
                    "annotator_evaluation_minimum_score": None,
                    "finished_task_number": "integer",
                    "task_number": "integer",
                    "control_weights": None,
                    "queue_done": None,
                    "show_ground_truth_first": None,
                    "assignment_settings": {"id": "integer"},
                    "require_comment_on_skip": None,
                    "ground_truth_number": "integer",
                    "skip_queue": None,
                    "workspace_title": None,
                    "sampling": None,
                    "queue_total": None,
                    "is_published": None,
                    "description": None,
                }
            },
        ),
    }
    response = client.prompts.compatible_projects()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.prompts.compatible_projects()
    validate_response(async_response, expected_response, expected_types)
