# This file was auto-generated by Fern from our API Definition.

from ....core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic


class MembersListResponseItem(UniversalBaseModel):
    user: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    User ID of the workspace member
    """

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic.Extra.allow
