imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    list:
      path: /api/storages/export/localfiles
      method: GET
      auth: true
      docs: Get a list of all local file export storage connections.
      source:
        openapi: openapi/openapi.yaml
      display-name: Get all export storage
      request:
        name: LocalListRequest
        query-parameters:
          ordering:
            type: optional<string>
            docs: Which field to use when ordering the results.
          project:
            type: optional<integer>
            docs: Project ID
      response:
        docs: ''
        type: list<root.LocalFilesExportStorage>
      examples:
        - response:
            body:
              - can_delete_objects: true
                created_at: '2024-01-15T09:30:00Z'
                description: description
                id: 1
                last_sync: '2024-01-15T09:30:00Z'
                last_sync_count: 1
                last_sync_job: last_sync_job
                meta:
                  key: value
                path: path
                project: 1
                regex_filter: regex_filter
                status: initialized
                synchronizable: true
                title: title
                traceback: traceback
                type: type
                use_blob_urls: true
      audiences:
        - public
    create:
      path: /api/storages/export/localfiles
      method: POST
      auth: true
      docs: Create a new local file export storage connection to store annotations.
      source:
        openapi: openapi/openapi.yaml
      display-name: Create export storage
      request:
        name: LocalCreateRequest
        body:
          properties:
            description:
              type: optional<string>
              docs: Storage description
            path:
              type: optional<string>
              docs: Path to local directory
            project:
              type: optional<integer>
              docs: Project ID
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            title:
              type: optional<string>
              docs: Storage title
              validation:
                maxLength: 2048
            use_blob_urls:
              type: optional<boolean>
              docs: >-
                Interpret objects as BLOBs and generate URLs. For example, if
                your directory contains images, you can use this option to
                generate URLs for these images. If set to False, it will read
                the content of the file and load it into Label Studio.
              default: false
        content-type: application/json
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - request: {}
          response:
            body:
              can_delete_objects: true
              created_at: '2024-01-15T09:30:00Z'
              description: description
              id: 1
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              meta:
                key: value
              path: path
              project: 1
              regex_filter: regex_filter
              status: initialized
              synchronizable: true
              title: title
              traceback: traceback
              type: type
              use_blob_urls: true
      audiences:
        - public
    validate:
      path: /api/storages/export/localfiles/validate
      method: POST
      auth: true
      docs: Validate a specific local file export storage connection.
      source:
        openapi: openapi/openapi.yaml
      display-name: Validate export storage
      request:
        name: LocalValidateRequest
        body:
          properties:
            description:
              type: optional<string>
              docs: Storage description
            id:
              type: optional<integer>
              docs: Storage ID. If set, storage with specified ID will be updated
            path:
              type: optional<string>
              docs: Path to local directory
            project:
              type: optional<integer>
              docs: Project ID
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            title:
              type: optional<string>
              docs: Storage title
              validation:
                maxLength: 2048
            use_blob_urls:
              type: optional<boolean>
              docs: >-
                Interpret objects as BLOBs and generate URLs. For example, if
                your directory contains images, you can use this option to
                generate URLs for these images. If set to False, it will read
                the content of the file and load it into Label Studio.
              default: false
        content-type: application/json
      examples:
        - request: {}
      audiences:
        - public
    get:
      path: /api/storages/export/localfiles/{id}
      method: GET
      auth: true
      docs: Get a specific local file export storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Get export storage
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              can_delete_objects: true
              created_at: '2024-01-15T09:30:00Z'
              description: description
              id: 1
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              meta:
                key: value
              path: path
              project: 1
              regex_filter: regex_filter
              status: initialized
              synchronizable: true
              title: title
              traceback: traceback
              type: type
              use_blob_urls: true
      audiences:
        - public
    delete:
      path: /api/storages/export/localfiles/{id}
      method: DELETE
      auth: true
      docs: Delete a specific local file export storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Delete export storage
      examples:
        - path-parameters:
            id: 1
      audiences:
        - public
    update:
      path: /api/storages/export/localfiles/{id}
      method: PATCH
      auth: true
      docs: Update a specific local file export storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Update export storage
      request:
        name: LocalUpdateRequest
        body:
          properties:
            description:
              type: optional<string>
              docs: Storage description
            path:
              type: optional<string>
              docs: Path to local directory
            project:
              type: optional<integer>
              docs: Project ID
            regex_filter:
              type: optional<string>
              docs: Regex for filtering objects
            title:
              type: optional<string>
              docs: Storage title
              validation:
                maxLength: 2048
            use_blob_urls:
              type: optional<boolean>
              docs: >-
                Interpret objects as BLOBs and generate URLs. For example, if
                your directory contains images, you can use this option to
                generate URLs for these images. If set to False, it will read
                the content of the file and load it into Label Studio.
              default: false
        content-type: application/json
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - path-parameters:
            id: 1
          request: {}
          response:
            body:
              can_delete_objects: true
              created_at: '2024-01-15T09:30:00Z'
              description: description
              id: 1
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              meta:
                key: value
              path: path
              project: 1
              regex_filter: regex_filter
              status: initialized
              synchronizable: true
              title: title
              traceback: traceback
              type: type
              use_blob_urls: true
      audiences:
        - public
    sync:
      path: /api/storages/export/localfiles/{id}/sync
      method: POST
      auth: true
      docs: Sync tasks from a local file export storage connection.
      source:
        openapi: openapi/openapi.yaml
      path-parameters:
        id: integer
      display-name: Sync export storage
      response:
        docs: ''
        type: root.LocalFilesExportStorage
      examples:
        - path-parameters:
            id: 1
          response:
            body:
              can_delete_objects: true
              created_at: '2024-01-15T09:30:00Z'
              description: description
              id: 1
              last_sync: '2024-01-15T09:30:00Z'
              last_sync_count: 1
              last_sync_job: last_sync_job
              meta:
                key: value
              path: path
              project: 1
              regex_filter: regex_filter
              status: initialized
              synchronizable: true
              title: title
              traceback: traceback
              type: type
              use_blob_urls: true
      audiences:
        - public
  source:
    openapi: openapi/openapi.yaml
